import PDFDocument from 'pdfkit'

export function generateNdaCertificate({
  fullName,
  email,
  ipAddress,
  signedAt,
  ndaVersion,
  applicationId,
}: {
  fullName: string
  email: string
  ipAddress: string
  signedAt: Date
  ndaVersion: string
  applicationId: string
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'LETTER' })
    const chunks: Buffer[] = []

    doc.on('data', chunk => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const formattedDate = signedAt.toLocaleString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
    })

    // Header
    doc
      .fontSize(10)
      .fillColor('#888888')
      .text('THE E.V.E. STUDIO', { characterSpacing: 2 })
      .moveDown(0.3)
      .fontSize(20)
      .fillColor('#000000')
      .font('Helvetica-Bold')
      .text('NDA Signature Certificate')
      .moveDown(0.2)
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#555555')
      .text('Beta Tester Non-Disclosure Agreement — Electronic Signature Record')
      .moveDown(1.5)

    // Divider
    doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor('#dddddd').stroke().moveDown(1)

    // Signature details
    const row = (label: string, value: string) => {
      doc
        .fontSize(9).fillColor('#888888').font('Helvetica-Bold')
        .text(label.toUpperCase(), { characterSpacing: 0.5 })
        .fontSize(12).fillColor('#000000').font('Helvetica')
        .text(value)
        .moveDown(0.8)
    }

    row('Signatory Name', fullName)
    row('Email Address', email)
    row('Signed On', formattedDate)
    row('IP Address', ipAddress)
    row('NDA Version', ndaVersion)
    row('Application ID', applicationId)
    row('Document', 'E.V.E. Studio Beta Tester NDA — https://www.theevestudio.io/E.V.E._studio__beta_tester_nda.pdf')

    // Divider
    doc.moveDown(0.5)
    doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor('#dddddd').stroke().moveDown(1)

    // Legal notice
    doc
      .fontSize(9)
      .fillColor('#777777')
      .font('Helvetica')
      .text(
        'This certificate constitutes a legally binding electronic signature record under the Electronic Signatures in Global and National Commerce Act (ESIGN Act, 15 U.S.C. § 7001 et seq.) and the Uniform Electronic Transactions Act (UETA). ' +
        'The signatory indicated above agreed to the terms of the E.V.E. Studio Beta Tester NDA by typing their full legal name and checking the confirmation box on the signing page. ' +
        'The timestamp, IP address, and user identification recorded herein serve as evidence of the signatory\'s intent to be bound by the agreement.',
        { lineGap: 3 }
      )
      .moveDown(1.5)

    // Footer
    doc
      .fontSize(8)
      .fillColor('#aaaaaa')
      .text(`Generated by E.V.E. Studio · theevestudio.io · ${new Date().toISOString()}`, { align: 'center' })

    doc.end()
  })
}
