import { createAdminClient } from '@/lib/supabase/admin'
import { notFound } from 'next/navigation'
import Image from 'next/image'
import ClientView from './ClientView'

export default async function ClientSharePage({ params }: { params: Promise<{ theme_id: string }> }) {
  const { theme_id } = await params
  const admin = createAdminClient()

  const [{ data: theme }, { data: scripts }] = await Promise.all([
    admin.from('themes').select('client_name, industry').eq('id', theme_id).single(),
    admin.from('scripts').select('*').eq('theme_id', theme_id).order('created_at', { ascending: false }),
  ])

  if (!theme || !scripts?.length) notFound()

  return (
    <div className="min-h-screen bg-black text-white">
      <nav className="border-b border-zinc-900 px-6 py-4">
        <Image src="/logo-full.png" alt="The E.V.E. Studio" width={160} height={26} />
      </nav>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <div className="mb-8">
          {theme.industry && (
            <p className="text-violet-400 text-xs font-semibold uppercase tracking-widest mb-2">{theme.industry}</p>
          )}
          <h1 className="text-3xl font-bold mb-2">{theme.client_name}</h1>
          <p className="text-zinc-500 text-sm">
            Here are your scripts — heart the ones you love so your editor knows which to film first.
          </p>
        </div>

        <ClientView scripts={scripts} themeId={theme_id} />

        <div className="mt-12 pt-8 border-t border-zinc-900 flex items-center justify-between">
          <p className="text-zinc-600 text-xs">Generated by VIBE · The E.V.E. Studio</p>
          <a href="/" className="text-violet-400 hover:text-violet-300 text-xs transition">theevestudio.io</a>
        </div>
      </main>
    </div>
  )
}
