import { createAdminClient } from '@/lib/supabase/admin'
import { notFound } from 'next/navigation'
import Image from 'next/image'

export default async function SharedScriptPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const admin = createAdminClient()

  const { data: script } = await admin
    .from('scripts')
    .select('*, themes(client_name)')
    .eq('id', id)
    .single()

  if (!script) notFound()

  const content = script.script_content
  const clientName = (script.themes as any)?.client_name || null

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Nav */}
      <nav className="border-b border-zinc-900 px-6 py-4 flex items-center justify-between">
        <Image src="/logo-full.png" alt="The E.V.E. Studio" width={160} height={26} />
        <a
          href={`/dashboard/scripts/${id}/print?print=1`}
          target="_blank"
          className="text-sm text-zinc-400 hover:text-white transition border border-zinc-700 hover:border-zinc-500 px-3 py-1.5 rounded-lg"
        >
          Export PDF
        </a>
      </nav>

      <main className="max-w-2xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="mb-8">
          {clientName && (
            <p className="text-violet-400 text-xs font-semibold uppercase tracking-widest mb-2">{clientName}</p>
          )}
          <h1 className="text-3xl font-bold leading-tight mb-4">{script.title || 'Untitled Script'}</h1>
          <div className="flex items-center gap-3 flex-wrap">
            {script.virality_score && (
              <span className="text-xs bg-violet-900 text-violet-300 px-3 py-1 rounded-full font-semibold">{script.virality_score}/10 virality</span>
            )}
            {script.hook_type && (
              <span className="text-xs bg-zinc-800 text-zinc-400 px-3 py-1 rounded-full">{script.hook_type}</span>
            )}
            {content?.duration_estimate && (
              <span className="text-xs text-zinc-500">{content.duration_estimate}</span>
            )}
          </div>
        </div>

        <div className="space-y-6">
          {/* Hook */}
          <div className="bg-violet-950/30 border border-violet-800 rounded-xl p-6">
            <p className="text-xs text-violet-400 font-semibold uppercase tracking-widest mb-3">Hook</p>
            <p className="text-white text-xl font-bold leading-relaxed">{content?.hook}</p>
          </div>

          {/* Body */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6">
            <p className="text-xs text-zinc-500 font-semibold uppercase tracking-widest mb-3">Body</p>
            <div className="space-y-2">
              {content?.body?.map((line: string, i: number) => (
                <p key={i} className="text-zinc-300 text-base leading-relaxed">{line}</p>
              ))}
            </div>
          </div>

          {/* CTA */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6">
            <p className="text-xs text-zinc-500 font-semibold uppercase tracking-widest mb-3">Call to Action</p>
            <p className="text-white text-base font-semibold">{content?.cta}</p>
          </div>

          {/* B-roll */}
          {content?.b_roll_notes && content.b_roll_notes.length > 0 && (
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6">
              <p className="text-xs text-zinc-500 font-semibold uppercase tracking-widest mb-3">B-Roll Notes</p>
              <ul className="space-y-1">
                {content.b_roll_notes.map((note: string, i: number) => (
                  <li key={i} className="text-zinc-400 text-sm">· {note}</li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-zinc-900 flex items-center justify-between">
          <p className="text-zinc-600 text-xs">Generated by VIBE · The E.V.E. Studio</p>
          <a href="/" className="text-violet-400 hover:text-violet-300 text-xs transition">theevestudio.io</a>
        </div>
      </main>
    </div>
  )
}
